apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-execution-config
  namespace: oficina
data:
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: "27017"
  MONGODB_DB: "oficina_execution"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  KEYCLOAK_ISSUER: "http://keycloak:8080/realms/oficina"
